version: '3'
services:
  spring-boot:
    container_name: piooda-server
    build:
      context: .
      dockerfile: Dockerfile-dev
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"